### ISSUE TITLE
Add Curses

### ISSUE THREAD

**Issue by gtalarico** [gtalarico/pipenv-pipes#6]
Wolud be nice to support for curses selection.

There is a working example [in this branch](https://github.com/gtalarico/pipenv-pipes/tree/curses-picker):

![curses-demo](https://raw.githubusercontent.com/gtalarico/pipenv-pipes/curses-picker/docs/static/pipes-gif-curses.gif)

## Todo
- [ ] Check Windows Compat with branch curses-picker. Might need windows binaries
- [ ] Port + Patch [Picker](https://github.com/wong2/pick/blob/master/pick/__init__.py)
- [ ] Add Color Support
- [ ] Add option to disable and fall back

### Curses Windows Support Resources
[Python Doc](https://docs.python.org/3.3/howto/curses.html#what-is-curses)
[Windows Wheels](https://stackoverflow.com/a/44355902)

[asciimatics](http://asciimatics.readthedocs.io/en/stable/)

**Comment by gtalarico** [comment]
Implemented on 0.5.0
